import React from "react";
import type { NextPage, InferGetStaticPropsType } from "next";
import Head from "next/head";
import Link from "next/link";

// Singleton
import NotionClient, { isText, PageProperty } from "../lib/notion";

type PagePropertyKey =
  | "tags"
  | "tldr"
  | "highlighted"
  | "date"
  | "published"
  | "category"
  | "name";

export type PageProperties = {
  tags: PageProperty<"multi_select">;
  tldr: PageProperty<"rich_text">;
  highlighted: PageProperty<"checkbox">;
  date: PageProperty<"date">;
  published: PageProperty<"checkbox">;
  category: PageProperty<"select">;
  name: PageProperty<"title">;
};

const propertyKeys = [
  "tags",
  "tldr",
  "highlighted",
  "date",
  "published",
  "category",
  "name",
];

export const getStaticProps = async () => {
  const notion = new NotionClient();

  const posts = await notion.postsHighlighted<{ properties: PageProperties }>();
  const publishedDate = new Date().toLocaleDateString();
  return {
    props: {
      posts,
      publishedDate,
    },
  };
};

const PageHome: NextPage<InferGetStaticPropsType<typeof getStaticProps>> = ({
  posts,
  publishedDate,
}) => {
  return (
    <>
      <Head>
        <title>/var/log/</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <h1>{"/var/log"}</h1>
      </header>

      <main>
        <div>
          <ul>
            {typeof posts !== "undefined" &&
              posts.map(({ properties, id }) => {
                const {
                  tags,
                  tldr,
                  highlighted,
                  date,
                  published,
                  category,
                  name,
                } = properties;
                return (
                  <li key={id}>
                    <Link href={"/posts/" + id}>
                      <a>
                        <article id={id}>
                          <h3>
                            {name.title
                              .filter(isText)
                              .map(({ text }) => text.content)}
                          </h3>
                          <p>{date.date!.start}</p>
                          <p>
                            {tldr.rich_text
                              .filter(isText)
                              .map(({ text }) => text.content)
                              .join("\n")}
                          </p>
                        </article>
                      </a>
                    </Link>
                  </li>
                );
              })}
          </ul>
        </div>
      </main>

      <footer>
        <p>{publishedDate}</p>
      </footer>
    </>
  );
};

export default PageHome;
